# https://golangci-lint.run/usage/configuration/
version = 2

[run]
timeout = "5m"

[linters]
disable-all = false
enable = [
  "revive",
  "govet",
  "errcheck", 
  "staticcheck"
]

[formatters]
enable = ["gofmt"]

[issues]

[[issues.exclude-rules]]
path = "_test\\.go"
linters = ["errcheck"]