# https://golangci-lint.run/usage/configuration/
version: 2

run:
  timeout: 5m

linters-settings:
  gofmt:
    simplify: true

linters:
  enable:
    - revive
    - govet
    - errcheck
    - staticcheck

formatters:
  enable:
    - gofmt

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck