# https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m

linters:
  disable-all: false
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
