version: '2'

run:
  timeout: 5m

linters:
  enable:
    - errcheck     # Detect unchecked errors
    - govet        # Examine Go source code for suspicious constructs
    - ineffassign  # Detect ineffectual assignments
    - staticcheck  # Go static analysis tool
    - unused       # Check for unused constants, variables, functions and types
    - revive       # Fast, configurable, extensible, flexible, and beautiful linter
    - misspell     # Fix spelling errors
    - gosec        # Security checker
    - unconvert    # Remove unnecessary type conversions
    - whitespace   # Check for unnecessary whitespace
    - godot        # Check if comments end in a period
    - gocyclo      # Checks cyclomatic complexity
    - prealloc     # Find slice declarations that could be preallocated
    
formatters:
  enable:
    - gofmt
    - goimports
