version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/quad-ops
    binary: quad-ops
    targets:
      - linux_amd64_v1
      - linux_arm64
      - linux_arm_7
      - darwin_amd64_v1
      - darwin_arm64
    ldflags:
      - -s -w
      - -X github.com/trly/quad-ops/internal/buildinfo.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    tags:
      - exclude_graphdriver_btrfs
      - exclude_graphdriver_devicemapper
      - containers_image_openpgp

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
