baseURL = 'https://trly.github.io/quad-ops'
languageCode = 'en-us'
title = 'quad-ops'
contentDir = './content'
enableEmoji = true
disableKinds = ['taxonomy']

[params]
  BookTheme = 'auto'
  BookLogo = 'images/quad-ops.svg'
  BookRepo = 'https://github.com/trly/quad-ops'
  BookEditPath = "edit/main/docs"
  BookComments = false

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

