version: '3.8'

services:
  db:
    image: docker.io/library/mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_ROOT_PASSWORD=root_password
    restart: always
    networks:
      - db-network

volumes:
  db-data:

networks:
  db-network:
    driver: bridge